# Generated by Django 5.2 on 2025-04-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Immage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='immage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='immage',
            new_name='image',
        ),
    ]
