# Generated by Django 5.2 on 2025-04-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='main.book'),
        ),
    ]
